import os
application_dir = os.path.dirname(__file__)
database_url = 'postgresql://localhost/test'
#database_url = 'postgresql://aldemo:reco!aldemo@aldemo.c6ppf7ztwoya.us-west-2.rds.amazonaws.com:5432/aldemo'
csv_file = application_dir + '/../../data/test.csv'
tab_csv_file = application_dir + '/../../data/test_tab_unix.txt'
excel_file = application_dir + '/../../data/monthly_test.xlsx'
sheet_in_excel_file = 'Monthly Site Listing'
table_name = 'monthly_sample'
db_flavor = 'postgres'
fig_dir = application_dir + '/static/figures/'
#db_flavor = 'mysql'
primary_brands = frozenset(['AVASTIN'])
other_brands = frozenset(['VECTIBIX', 'ERBITUX'])
m1_month_year = "Jan 16"
months_to_store = frozenset(['M1', 'M2', 'M3', 'M4', 'M5', 'M6'])
#rN_sales = frozenset([1, 3, 6, 12])
rN_sales = frozenset([3, 6])
rN_growth_value = frozenset([3])
rN_growth_pct = frozenset([3])